### ISSUE TITLE
Certain mods fail to be added from Curseforge

### ISSUE THREAD

**Issue by A-noximous** [theRookieCoder/ferium#88] opened 2022-05-19 04:57 UTC
While most mods are added successfully from Modrinth, Github and Curseforge, [Effective](https://www.curseforge.com/minecraft/mc-mods/effective) and [Entity Culling](https://www.curseforge.com/minecraft/mc-mods/entityculling) failed with:
 `Adding mod... error decoding response body: invalid type: null, expected a string at line 1 column 1910` and `... line 1 column 410` respectively with and without ` --dont-check-mod-loader` and `--dont-check-game-version`.
Is it an issue with Ferium, Curseforge or am I just doing something wrong? I attempted to add the mods with `ferium.exe add-curseforge 556381` and `ferium.exe add-curseforge 448233`.

**Comment by theRookieCoder** [comment] 2022-05-19 05:03
Duplicate of #86, will be fixed in v4

**Closed by theRookieCoder** 2022-05-19 05:03 UTC
