### ISSUE TITLE
Upgrading mods doesn't work without modrinth mod in profile

### ISSUE THREAD

**Issue by Demmos** [theRookieCoder/ferium#8] opened 2022-01-25 11:29 UTC
`ferium upgrade` gives profile is empty error if all your mods are sourced from CurseForge if you add a mod from modrinth it recognizes every mod

**Comment by Demmos** [comment] 2022-01-25 12:03
To add to this, CurseForge mods are not recognized via `ferium list` but are recognized via `ferium profile list`, also it only doesn't recognize CurseForge mods if either a GitHub repo or modrinth mod aren't present

**Comment by theRookieCoder** [comment] 2022-01-25 12:34
Duplicate of #7, fixed in 6656e9dd9a846f6cbf01298bd99e524dda2432a2 by #2

**Closed by theRookieCoder** 2022-01-25 12:34 UTC

**Comment by theRookieCoder** [comment] 2022-01-26 03:17
`ferium list` and `ferium upgrade` use the same faulty function to check if there are mods configured. `ferium profile list` does not care if mods are configured or not, it'll just show zeroes if there are none
